### ISSUE TITLE
Is takes_args=true a good default?

### ISSUE THREAD

**Issue by meator** [crazy-complete/crazy-complete#7]
Here is a simple crazy-complete input file:

```yaml
prog: "example"
options:
  - option_strings: ["--flag"]
```

As it stands now, this flag is assumed to take an argument which crazy-complete cannot complete and which has to be specified manually.

This is the "simplest and default" behavior, but it expresses a pretty rare situation. In most cases, the flag either doesn't have an argument or has an argument that can be completed with `complete`. It should be rare that there is a flag with an argument that cannot be completed.

It might be wiser to have `takes_args=false` as the default. I believe that flags which don't take any argument are pretty common in CLI utilities. With the current default, you have to explicitly specify `takes_args=false` after every option which doesn't have any arguments, which is annoying.

Here is a redesign that could be more practical:

### First example
```yaml
prog: "example"
options:
  - option_strings: ["--flag"]
```

`--flag` takes no arguments.

Here you can see that the "simplest and default" behavior expresses a more useful state.

### Second example
```yaml
prog: "example"
options:
  - option_strings: ["--flag"]
    complete: ["file"]
```

`--flag` takes an argument, which is a file.

### Third example
```yaml
prog: "example"
options:
  - option_strings: ["--flag"]
    complete: ["none"]
```

`--flag` takes an argument, but crazy-complete cannot provide suggestions. This is the same behavior like specifying an option without `takes_args` and `complete` under the current system (this is the first code block in this issue).

---

This design could be problematic, because

```yaml
prog: "example"
options:
  - option_strings: ["--flag"]
    complete: ["none"]
```

and

```yaml
prog: "example"
options:
  - option_strings: ["--flag"]
```

would mean different things with my redesign. I'm not saying that my design is perfect, it is a proof of concept.

None of my three examples have `takes_args` in them. An option with `complete` implies `takes_args`, I think that `takes_args` is redundant.

This is more of a discussion topic than an issue (I would create a GitHub discussion if they were enabled in this repo). What do you think?
